import { useEffect, useState } from "react";
import { api } from "../../api.js";
import { useAuth } from "../../context/AuthContext.jsx";
const options=["PURCHASE_ORDER","PURCHASE_INVOICE","SALES_INVOICE","PAYMENT","JOURNAL","WORK_COST","STOCK_TRANSFER","WASTE"];
export default function Approvals({notify}){
  const {user}=useAuth(),admin=["admin","company_admin"].includes(user?.role);
  const [data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>setData(await api("/erp/approvals"));
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function run(action){setBusy(true);setError("");try{await action();await load();notify("Approval queue updated");}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(!data)return <p>{error||"Loading approval queue…"}</p>;
  return <section className="erp-card"><h2>Independent document approvals</h2>{error&&<p className="erp-error">{error}</p>}<p>Submit a document from New document. A different company administrator reviews and posts the frozen proposal. Failed postings stay approved for review/retry; posting still validates stock, credit limits and document links.</p>{admin&&<form key={JSON.stringify(data.settings)} onSubmit={e=>{e.preventDefault();const f=e.currentTarget,values=new FormData(f);run(()=>api("/erp/approvals/settings",{method:"POST",body:JSON.stringify({enabled:values.get("enabled")==="on",threshold:values.get("threshold"),types:values.getAll("types")})}));}}><label><input type="checkbox" name="enabled" defaultChecked={data.settings?.approvalThreshold!==null&&data.settings?.approvalThreshold!==undefined}/>Enforce approval at threshold</label><label className="erp-field"><span>Threshold INR (0 = all selected postings)</span><input type="number" name="threshold" min="0" step="0.01" defaultValue={(data.settings?.approvalThreshold||0)/100}/></label><div className="erp-grid">{options.map(t=><label key={t}><input type="checkbox" name="types" value={t} defaultChecked={(data.settings?.approvalTypes||[]).includes(t)}/>{t.replaceAll("_"," ")}</label>)}</div><button disabled={busy}>Save company approval policy</button></form>}<button disabled={busy} onClick={()=>run(async()=>{})}>Refresh requests</button>{data.requests.map(r=><article className="erp-card" key={r._id}><h3>{r.input.type.replaceAll("_"," ")} · {r.status}</h3><p>Requested by: {r.requestedBy}<br/>Party: {r.input.partyCode||"—"} · Date: {r.input.date||"Posting date"}<br/>Source: {r.input.sourceId||"—"}<br/>{r.input.notes}</p><div className="erp-table"><table><thead><tr><th>SKU / Account</th><th>Quantity / Debit</th><th>Rate / Credit</th></tr></thead><tbody>{(r.input.lines||[]).map((l,i)=><tr key={i}><td>{l.sku}</td><td>{l.quantity}</td><td>{l.rate}</td></tr>)}{(r.input.journalLines||[]).map((l,i)=><tr key={`j${i}`}><td>{l.account}</td><td>{l.debit}</td><td>{l.credit}</td></tr>)}</tbody></table></div>{r.input.amount&&<p>Amount: ₹{r.input.amount}</p>}<p>Decision: {r.decidedBy||"Pending"} · {r.reason||""}<br/>Posted ID: {r.documentId||"—"}</p>{admin&&r.requestedBy!==user.userId&&["PENDING","APPROVED"].includes(r.status)&&<form onSubmit={e=>{e.preventDefault();const action=e.nativeEvent.submitter.value,reason=e.currentTarget.elements.reason.value;run(()=>api(`/erp/approvals/${r._id}/decision`,{method:"POST",body:JSON.stringify({action,reason})}));}}><input name="reason" required placeholder="Review / decision notes"/><button value={r.status==="PENDING"?"APPROVE":"POST"} disabled={busy}>Review and post</button>{r.status==="PENDING"&&<button value="REJECT" disabled={busy}>Reject</button>}</form>}</article>)}</section>;
}
