import { useEffect, useState } from "react";
import { api } from "../../api.js";
import { useAuth } from "../../context/AuthContext.jsx";
import "./erp.css";
function Retry({ kind, id, busy, run }) {
  return <form onSubmit={e => { e.preventDefault(); const confirm = e.currentTarget.elements.confirm.value; run(() => api(`/automation/retry/${kind}/${id}`, { method: "POST", body: JSON.stringify({ confirm }) })); }}><input name="confirm" required placeholder="Type RETRY REVIEWED JOB after provider review" /><button disabled={busy}>Retry reviewed request</button></form>;
}
export default function AutomationPage({ notify }) {
  const { user } = useAuth(), owner = user?.role === "saas_super_admin";
  const [data, setData] = useState(null), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ kind: "CANCEL", billingId: "", reason: "" });
  async function load() { setData(await api("/automation/status")); }
  useEffect(() => { load().catch(e => setError(e.message)); }, []);
  const run = async action => { setError(""); setBusy(true); try { await action(); await load(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <div className="erp-shell"><header className="erp-header"><div><span className="erp-eyebrow">UG SAAS · BILLING OPERATIONS</span><h1>Subscription automation</h1><p>Payment processing, queued invoice emails and subscription requests</p></div><button disabled={busy} onClick={() => run(load)}>Refresh</button></header>{error && <p className="erp-error">{error}</p>}
    <section className="erp-card"><p>Worker: <b>{data?.enabled ? "Enabled · runs every minute" : "Disabled"}</b>. Renewal reminders do not automatically charge a card. Company data remains stored after expiry/cancellation.</p></section>
    {!owner && <section className="erp-card"><h2>Request cancellation or full refund</h2><form onSubmit={e => { e.preventDefault(); run(async () => { await api("/automation/requests", { method: "POST", body: JSON.stringify(form) }); notify("Request submitted for owner review"); }); }}><div className="erp-grid"><label>Action<select value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value })}><option value="CANCEL">Cancel renewal reminders at end of paid term</option><option value="REFUND">Request full refund</option></select></label>{form.kind === "REFUND" && <label>Paid subscription<select required value={form.billingId} onChange={e => setForm({ ...form, billingId: e.target.value })}><option value="">Select payment</option>{(data?.billing || []).filter(b => b.status === "PAID").map(b => <option key={b._id} value={b._id}>{b.referenceNo} · {b.plan} · INR {b.amount}</option>)}</select></label>}<label>Reason<textarea required value={form.reason} onChange={e => setForm({ ...form, reason: e.target.value })} /></label></div><button disabled={busy}>Submit request</button></form></section>}
    <section className="erp-card"><h2>Requests</h2>{(data?.actions || []).map(row => <article className="erp-card" key={row._id}><b>{row.kind} · {row.companyKey} · {row.status}</b><p>{row.reason}</p><p>Billing ID: {row.billingId || "—"} · INR {Number(row.amount || 0).toFixed(2)} · Provider/reference: {row.providerId || "—"}</p>{owner && row.status === "REQUESTED" && <form onSubmit={e => { e.preventDefault(); const fields = e.currentTarget.elements; run(async () => { await api(`/automation/requests/${row._id}/decide`, { method: "POST", body: JSON.stringify({ decision: "APPROVE", confirm: fields.confirm?.value || "", manualReference: fields.reference?.value || "" }) }); notify("Approved request queued for worker"); }); }}>{row.kind === "REFUND" && <><p>Approval can trigger a real Razorpay refund when automation is enabled. For manual payments, complete the bank payout separately and record its reference.</p><input name="confirm" required placeholder="Type APPROVE FULL REFUND" /><input name="reference" placeholder="Manual refund payout reference (manual payments only)" /></>}<button disabled={busy}>Approve</button> <button type="button" disabled={busy} onClick={() => run(() => api(`/automation/requests/${row._id}/decide`, { method: "POST", body: JSON.stringify({ decision: "REJECT" }) }))}>Reject</button></form>}{owner && row.status === "FAILED" && <Retry kind="action" id={row._id} busy={busy} run={run} />}{row.lastError && <p>Last failure: {row.lastError}. Review provider/worker records before retrying.</p>}</article>)}</section>
    <section className="erp-card"><h2>Invoice email queue</h2><div className="erp-table"><table><thead><tr><th>Company</th><th>State</th><th>Attempts</th><th>Sent</th><th>Last error</th></tr></thead><tbody>{(data?.email || []).map(r => <tr key={r._id}><td>{r.companyKey}</td><td>{r.status}</td><td>{r.attempts}</td><td>{r.sentAt ? new Date(r.sentAt).toLocaleString() : "—"}</td><td>{r.lastError || "—"}{owner && r.status === "DEAD" && <Retry kind="email" id={r._id} busy={busy} run={run} />}</td></tr>)}</tbody></table></div></section>
    {owner && <section className="erp-card"><h2>Verified payment inbox</h2><div className="erp-table"><table><thead><tr><th>Event</th><th>Status</th><th>Attempts</th><th>Last failure</th></tr></thead><tbody>{(data?.payments || []).map(r => <tr key={r._id}><td>{r.key}</td><td>{r.status}</td><td>{r.attempts}</td><td>{r.lastError || "—"}{r.status === "DEAD" && <Retry kind="payment" id={r._id} busy={busy} run={run} />}</td></tr>)}</tbody></table></div></section>}
  </div>;
}
