import {useEffect,useState} from "react";
import {api} from "../../api.js";
import {useAuth} from "../../context/AuthContext.jsx";
export default function BankReconciliation({notify}){
 const {user}=useAuth(),write=["company_admin","admin"].includes(user?.role)||(user?.permissions||[]).includes("erp.reconcile");
 const [rows,setRows]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const load=async()=>setRows(await api("/erp/bank"));useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function run(fn){setBusy(true);setError("");try{await fn();await load();notify("Bank reconciliation updated");}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <section className="erp-card"><h2>Bank statement import & reviewed matching</h2>{error&&<p className="erp-error">{error}</p>}<p>CSV header: date,reference,amount. Date format YYYY-MM-DD. Positive INR = money received; negative INR = money paid. This release uses a single BANK ledger per factory; references must be unique. Import does not create accounting entries or automatically match payments.</p>{write&&<form onSubmit={e=>{e.preventDefault();const file=e.currentTarget.elements.file.files[0];run(async()=>{if(!file||file.size>500000)throw new Error("Choose a CSV smaller than 500 KB");await api("/erp/bank/import",{method:"POST",body:JSON.stringify({csv:await file.text()})});});}}><input type="file" name="file" accept=".csv,text/csv" required/><button disabled={busy}>Import reviewed bank CSV</button></form>}<button onClick={()=>run(async()=>{})} disabled={busy}>Refresh</button><div className="erp-table"><table><thead><tr><th>Date</th><th>Reference</th><th>Signed INR</th><th>Matched document ID</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r._id}><td>{r.date}</td><td>{r.reference}</td><td>{(r.amount/100).toFixed(2)}</td><td>{r.documentId||"Unmatched"}</td><td>{write&&(!r.documentId?<form onSubmit={e=>{e.preventDefault();const documentId=e.currentTarget.elements.documentId.value;run(()=>api(`/erp/bank/${r._id}/match`,{method:"POST",body:JSON.stringify({documentId})}));}}><input name="documentId" required placeholder="Posted ERP document ID"/><button disabled={busy}>Match</button></form>:<form onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));run(()=>api(`/erp/bank/${r._id}/unmatch`,{method:"POST",body:JSON.stringify(v)}));}}><input name="confirm" required placeholder="Type UNMATCH BANK"/><input name="reason" required placeholder="Review reason"/><button disabled={busy}>Unmatch</button></form>)}</td></tr>)}</tbody></table></div></section>;
}
