import { useEffect, useRef, useState } from "react";
import { api } from "../../api.js";
import { useAuth } from "../../context/AuthContext.jsx";
import "./erp.css";
const amount = n => n === null || n === undefined ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(Number(n || 0) / 100);
const q = n => (Number(n || 0) / 1000).toLocaleString("en-IN", { maximumFractionDigits: 3 });
const label = s => String(s || "").replaceAll("_", " ");
const emptyLine = { sku: "", quantity: "1", rate: "0", taxPercent: "0", location: "FABRIC", target: "CUTTING" };
const blankDoc = () => ({ type: "PURCHASE_ORDER", date: new Date().toISOString().slice(0, 10), partyCode: "", sourceId: "", bomCode: "", notes: "", qcNotes: "", amount: "", cashAccount: "BANK", lines: [{ ...emptyLine }], journalLines: [{ account: "BANK", debit: "0", credit: "0", party: "" }, { account: "OPENING_EQUITY", debit: "0", credit: "0", party: "" }] });
const sourceTypes = { SALES_ORDER: ["QUOTATION"], WORK_ORDER: ["SALES_ORDER"], GOODS_RECEIPT: ["PURCHASE_ORDER"], PURCHASE_INVOICE: ["GOODS_RECEIPT"], PURCHASE_RETURN: ["PURCHASE_INVOICE"], SALES_INVOICE: ["SALES_ORDER"], DISPATCH: ["SALES_INVOICE"], SALES_RETURN: ["DISPATCH"], MATERIAL_ISSUE: ["WORK_ORDER"], MATERIAL_RETURN: ["WORK_ORDER"], WORK_COST: ["WORK_ORDER"], PRODUCTION_RECEIPT: ["WORK_ORDER"], QC_RELEASE: ["PRODUCTION_RECEIPT", "JOBWORK_RECEIPT", "SALES_RETURN", "GOODS_RECEIPT"], QC_REJECT: ["PRODUCTION_RECEIPT", "JOBWORK_RECEIPT", "SALES_RETURN", "GOODS_RECEIPT"], JOBWORK_RECEIPT: ["JOBWORK_SEND"], RECEIPT: ["SALES_INVOICE"], PAYMENT: ["PURCHASE_INVOICE"] };
function Table({ headings, rows }) { return <div className="erp-table"><table><thead><tr>{headings.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={i}>{r.map((cell, n) => <td key={n}>{cell}</td>)}</tr>) : <tr><td colSpan={headings.length}>No records yet.</td></tr>}</tbody></table></div>; }
function Select({ value, onChange, options, empty = "Select…" }) { return <select value={value} onChange={e => onChange(e.target.value)}><option value="">{empty}</option>{options.map(o => <option key={typeof o === "string" ? o : o.value} value={typeof o === "string" ? o : o.value}>{typeof o === "string" ? label(o) : o.label}</option>)}</select>; }
function Field({ name, children }) { return <label className="erp-field"><span>{name}</span>{children}</label>; }

export default function ErpWorkspace({ notify }) {
  const { user } = useAuth();
  const [workspace, setWorkspace] = useState(null), [tab, setTab] = useState("Overview"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const [docs, setDocs] = useState([]), [stock, setStock] = useState([]), [entries, setEntries] = useState([]), [financials, setFinancials] = useState(null);
  const [form, setForm] = useState(blankDoc), [selected, setSelected] = useState(null), [masterKind, setMasterKind] = useState("skus"), [master, setMaster] = useState({}), [notes, setNotes] = useState("");
  const [sourceId, setSourceId] = useState(""), [reportDates, setReportDates] = useState({ from: `${new Date().getFullYear() - (new Date().getMonth() < 3 ? 1 : 0)}-04-01`, to: new Date().toISOString().slice(0, 10) });
  const requestKey = useRef(crypto.randomUUID());
  const canAdmin = ["company_admin", "admin"].includes(user?.role);
  const canFinance = canAdmin || user?.role === "management" || (user?.permissions || []).some(p => ["erp.accounts", "erp.finance.read"].includes(p));
  async function load() {
    const [w, d, s] = await Promise.all([api("/erp/workspace"), api("/erp/documents"), api("/erp/stock")]);
    setWorkspace(w); setDocs(d); setStock(s);
  }
  useEffect(() => { load().catch(e => setError(e.message)); }, []);
  const execute = async action => { setBusy(true); setError(""); try { await action(); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  const update = changes => { requestKey.current = crypto.randomUUID(); setForm(f => ({ ...f, ...changes })); };
  const updateLine = (i, changes) => update({ lines: form.lines.map((l, n) => n === i ? { ...l, ...changes } : l) });
  async function chooseSource(id) {
    setSourceId(id); if (!id) { update({ sourceId: "" }); return; }
    const source = await api(`/erp/documents/${id}`);
    let lines = source.lines.map(l => ({ sku: l.sku, quantity: l.qty / 1000, rate: l.rate / 100, taxPercent: l.taxBps / 100, location: l.location, target: "CUTTING" }));
    if (["MATERIAL_ISSUE", "MATERIAL_RETURN"].includes(form.type)) lines = source.metadata.bom.components.map(c => ({ ...emptyLine, sku: c.sku, quantity: Math.ceil(c.qty * source.lines[0].qty / source.metadata.bom.outputQty) / 1000, location: workspace.skus.find(s => s.code === c.sku)?.location || "FABRIC" }));
    update({ sourceId: id, partyCode: source.partyCode || "", lines });
  }
  async function submitDoc(event) {
    event.preventDefault();
    await execute(async () => {
      const body = { ...form };
      if (["RECEIPT", "PAYMENT", "WORK_COST", "JOURNAL"].includes(body.type)) body.lines = [];
      const posted = await api("/erp/documents", { method: "POST", headers: { "Idempotency-Key": requestKey.current }, body: JSON.stringify(body) });
      setSelected(posted); requestKey.current = crypto.randomUUID(); setForm(blankDoc()); await load(); setTab("Documents"); notify("ERP document posted with stock/accounting entries");
    });
  }
  async function report() {
    await execute(async () => {
      setFinancials(await api(`/erp/financials?${new URLSearchParams({ from: reportDates.from, to: `${reportDates.to}T23:59:59.999Z` })}`));
    });
  }
  if (!workspace) return <div className="erp-shell"><h2>Integrated ERP</h2><p>{error || "Loading workspace…"}</p></div>;
  const noItems = ["RECEIPT", "PAYMENT", "WORK_COST", "JOURNAL"].includes(form.type);
  const activeDocs = docs.filter(d => !d.reversedBy && (sourceTypes[form.type] || []).includes(d.type));
  return <div className="erp-shell">
    <header className="erp-header"><div><span className="erp-eyebrow">UG SAAS · {workspace.company.name}</span><h1>Integrated ERP</h1><p>{workspace.company.factory} · Stock, production and accounts in one posting flow</p></div><span className={`erp-badge ${workspace.settings.enabled ? "on" : ""}`}>{workspace.settings.enabled ? "ERP active · legacy entries locked" : "Opening balance review"}</span></header>
    <nav className="erp-tabs">{["Overview", "Masters", "New document", "Documents", "Stock", "Ledger", ...(canFinance ? ["Financials"] : [])].map(t => <button className={tab === t ? "active" : ""} key={t} onClick={() => { setTab(t); if (t === "Ledger") execute(async () => setEntries(await api("/erp/ledger"))); }}>{t}</button>)}</nav>
    {error && <p className="erp-error" role="alert">{error}</p>}
    {tab === "Overview" && <>
      <div className="erp-stats"><article><span>Current stock value</span><strong>{amount(stock.reduce((s, b) => s + b.value, 0))}</strong></article><article><span>Stock positions</span><strong>{stock.length}</strong></article><article><span>Recent documents</span><strong>{docs.length}</strong></article><article><span>Variant SKUs</span><strong>{workspace.skus.length}</strong></article></div>
      <section className="erp-card"><h2>Set up your factory</h2><ol><li>Create customer/supplier and variant SKU masters. Use separate codes for batch, colour, size and unit.</li><li>Create BOM versions for finished goods.</li><li>Review existing department stock; post OPENING documents with quantities and unit costs.</li><li>Activate once opening quantities and valuation match. Legacy entry screens then become read-only.</li></ol>
        {canAdmin && <button disabled={busy} onClick={() => execute(async () => { const snapshot = await api("/erp/migration-snapshot"); const url = URL.createObjectURL(new Blob([JSON.stringify(snapshot, null, 2)], { type: "application/json" })); const a = document.createElement("a"); a.href = url; a.download = "legacy-stock-review.json"; a.click(); URL.revokeObjectURL(url); })}>Download legacy stock review snapshot</button>}
        {!workspace.settings.enabled && canAdmin && <><Field name="Migration/reconciliation notes"><textarea value={notes} onChange={e => setNotes(e.target.value)} /></Field><button disabled={busy || !notes.trim()} onClick={() => execute(async () => { await api("/erp/activate", { method: "POST", body: JSON.stringify({ confirm: "OPENING BALANCES REVIEWED", notes }) }); await load(); })}>Activate ERP after reviewed opening balances</button></>}
        <p>Posted records cannot be edited or deleted. Reverse downstream records first, then post a correction. Opening balances lock on activation.</p>
      </section><section className="erp-card"><h2>Connected workflows</h2><p>Purchase order → Goods receipt → Purchase invoice → Payment</p><p>Quotation → Sales order → Sales invoice → Dispatch → Receipt</p><p>Work order → Material issue + Work cost → Production receipt → QC release/reject → Dispatch</p><p>Transfers, job work, waste and returns use the same stock/accounting ledger. Partial completions allocate material and work costs to each receipt; QC can release or reject each batch.</p></section>
    </>}
    {tab === "Masters" && <section className="erp-card"><h2>Company / factory masters</h2><Select value={masterKind} onChange={v => { setMasterKind(v); setMaster({}); }} options={[{ value: "skus", label: "Variant SKUs" }, { value: "parties", label: "Customers / Suppliers" }, { value: "boms", label: "BOM versions" }]} />
      <form onSubmit={e => { e.preventDefault(); execute(async () => { await api(`/erp/masters/${masterKind}`, { method: "POST", body: JSON.stringify({ ...master, ...(masterKind === "boms" ? { components: master.components || [] } : {}) }) }); setMaster({}); await load(); notify("Master saved"); }); }}>
        <div className="erp-grid">{(masterKind === "skus" ? ["code", "name", "unit", "batch", "colour", "size", "minimumQty"] : masterKind === "parties" ? ["code", "name", "email", "phone", "address", "gstin"] : ["code", "outputQuantity"]).map(k => <Field name={label(k)} key={k}><input required={["code", "name", "unit", "outputQuantity"].includes(k)} value={master[k] || ""} onChange={e => setMaster({ ...master, [k]: e.target.value })} /></Field>)}
          {masterKind !== "boms" && <Field name="Type"><Select value={master.kind || ""} onChange={v => setMaster({ ...master, kind: v })} options={masterKind === "skus" ? ["RAW", "FINISHED", "CONSUMABLE"] : ["CUSTOMER", "SUPPLIER", "BOTH"]} /></Field>}
          {masterKind === "skus" && <Field name="Default store"><Select value={master.location || ""} onChange={v => setMaster({ ...master, location: v })} options={workspace.locations.filter(l => l !== "WIP")} /></Field>}
          {masterKind === "boms" && <><Field name="Finished output SKU"><Select value={master.outputSku || ""} onChange={v => setMaster({ ...master, outputSku: v })} options={workspace.skus.filter(s => s.kind === "FINISHED").map(s => ({ value: s.code, label: `${s.code} · ${s.name}` }))} /></Field><fieldset><legend>BOM material quantities per output quantity</legend>{(master.components || [{ sku: "", quantity: "" }]).map((c, i) => <div className="erp-grid" key={i}><Select value={c.sku} options={workspace.skus.filter(s => s.code !== master.outputSku).map(s => ({ value: s.code, label: `${s.code} · ${s.unit}` }))} onChange={v => setMaster({ ...master, components: (master.components || [{ sku: "", quantity: "" }]).map((row, n) => n === i ? { ...row, sku: v } : row) })} /><input aria-label="Component quantity" type="number" required min="0.001" step="0.001" value={c.quantity} onChange={e => setMaster({ ...master, components: (master.components || [{ sku: "", quantity: "" }]).map((row, n) => n === i ? { ...row, quantity: e.target.value } : row) })} /><button type="button" onClick={() => setMaster({ ...master, components: (master.components || []).filter((_, n) => n !== i) })}>Remove</button></div>)}<button type="button" onClick={() => setMaster({ ...master, components: [...(master.components || [{ sku: "", quantity: "" }]), { sku: "", quantity: "" }] })}>Add material</button></fieldset></>}
        </div><button disabled={busy}>Save master</button></form>
      <Table headings={masterKind === "boms" ? ["BOM", "Output", "Components"] : ["Code", "Name", "Type", "Details"]} rows={workspace[masterKind].map(m => masterKind === "boms" ? [m.code, `${m.outputSku} / ${q(m.outputQty)}`, m.components.map(c => `${c.sku} × ${q(c.qty)}`).join(", ")] : [m.code, m.name, m.kind, masterKind === "skus" ? `${m.unit} · ${m.location} · ${m.batch || ""} ${m.colour || ""} ${m.size || ""}` : `${m.email || ""} ${m.phone || ""}`])} />
    </section>}
    {tab === "New document" && <section className="erp-card"><h2>Post document</h2><form onSubmit={submitDoc}>
      <div className="erp-grid"><Field name="Document type"><Select value={form.type} options={workspace.types} onChange={v => { update({ ...blankDoc(), type: v }); setSourceId(""); }} /></Field><Field name="Posting date"><input type="date" required value={form.date} onChange={e => update({ date: e.target.value })} /></Field><Field name="Customer / Supplier"><Select value={form.partyCode} options={workspace.parties.map(p => ({ value: p.code, label: `${p.code} · ${p.name}` }))} onChange={v => update({ partyCode: v })} /></Field>
        {sourceTypes[form.type] && <Field name="Source document"><Select value={form.sourceId} options={activeDocs.map(d => ({ value: d._id, label: d.number }))} onChange={v => execute(() => chooseSource(v))} /><input aria-label="Older source document ID" placeholder="Older document ID (from history)" value={sourceId} onChange={e => setSourceId(e.target.value)} /><button type="button" onClick={() => execute(() => chooseSource(sourceId))}>Load source</button></Field>}
        {form.type === "WORK_ORDER" && <Field name="BOM version"><Select value={form.bomCode} options={workspace.boms.map(b => b.code)} onChange={v => { const b = workspace.boms.find(b => b.code === v); update({ bomCode: v, lines: [{ ...emptyLine, sku: b?.outputSku || "", quantity: b?.outputQty / 1000 || 1, location: "FINISHED" }] }); }} /></Field>}
        {["RECEIPT", "PAYMENT", "WORK_COST"].includes(form.type) && <><Field name="Amount (INR)"><input type="number" min="0.01" step="0.01" required value={form.amount} onChange={e => update({ amount: e.target.value })} /></Field><Field name="Payment account"><Select value={form.cashAccount} onChange={v => update({ cashAccount: v })} options={form.type === "WORK_COST" ? ["BANK", "CASH", "AP"] : ["BANK", "CASH"]} /></Field></>}
      </div>
      {!noItems && <><div className="erp-table"><table><thead><tr><th>Variant SKU</th><th>Quantity</th><th>Unit rate INR</th><th>Tax %</th><th>From / Store</th><th>Transfer to</th><th /></tr></thead><tbody>{form.lines.map((l, i) => <tr key={i}><td><Select value={l.sku} options={workspace.skus.map(s => ({ value: s.code, label: `${s.code} · ${s.unit}` }))} onChange={v => updateLine(i, { sku: v, location: workspace.skus.find(s => s.code === v)?.location || "FABRIC" })} /></td><td><input type="number" step="0.001" min="0.001" required value={l.quantity} onChange={e => updateLine(i, { quantity: e.target.value })} /></td><td><input type="number" step="0.01" min="0" value={l.rate} onChange={e => updateLine(i, { rate: e.target.value })} /></td><td><input type="number" step="0.01" min="0" max="100" value={l.taxPercent} onChange={e => updateLine(i, { taxPercent: e.target.value })} /></td><td><Select value={l.location} options={workspace.locations.filter(l => l !== "WIP")} onChange={v => updateLine(i, { location: v })} /></td><td><Select value={l.target} options={workspace.locations.filter(l => l !== "WIP")} onChange={v => updateLine(i, { target: v })} /></td><td><button type="button" onClick={() => update({ lines: form.lines.filter((_, n) => n !== i) })}>Remove</button></td></tr>)}</tbody></table></div><button type="button" onClick={() => update({ lines: [...form.lines, { ...emptyLine }] })}>Add item line</button></>}
      {form.type === "JOURNAL" && <><div className="erp-table"><table><thead><tr><th>Account</th><th>Debit INR</th><th>Credit INR</th><th>Party code</th><th /></tr></thead><tbody>{form.journalLines.map((l, i) => <tr key={i}><td><Select value={l.account} options={Object.keys(workspace.accounts)} onChange={v => update({ journalLines: form.journalLines.map((j, n) => n === i ? { ...j, account: v } : j) })} /></td>{["debit", "credit", "party"].map(k => <td key={k}><input value={l[k]} onChange={e => update({ journalLines: form.journalLines.map((j, n) => n === i ? { ...j, [k]: e.target.value } : j) })} /></td>)}<td><button type="button" onClick={() => update({ journalLines: form.journalLines.filter((_, n) => n !== i) })}>Remove</button></td></tr>)}</tbody></table></div><button type="button" onClick={() => update({ journalLines: [...form.journalLines, { account: "BANK", debit: "0", credit: "0", party: "" }] })}>Add journal line</button></>}
      <div className="erp-grid"><Field name="Narration"><textarea value={form.notes} onChange={e => update({ notes: e.target.value })} /></Field>{form.type.startsWith("QC_") && <Field name="QC findings / inspection result"><textarea required value={form.qcNotes} onChange={e => update({ qcNotes: e.target.value })} /></Field>}</div>
      <p>Rates/taxes are inherited for linked receipts and invoices. Work-order material quantities follow the frozen BOM version. Check all fields before posting.</p><button disabled={busy}>{busy ? "Posting…" : "Post document"}</button>
    </form></section>}
    {tab === "Documents" && <section className="erp-card"><h2>Posted documents</h2><button onClick={() => execute(load)}>Refresh</button><Table headings={["Number", "Date", "Party", "Amount", "Status", "Actions"]} rows={docs.map(d => [d.number, new Date(d.date).toLocaleDateString("en-IN"), d.partyCode || "—", amount(d.totals.gross), d.reversedBy ? "Reversed" : "Posted", <button onClick={() => setSelected(d)}>View / Print</button>])} /><button disabled={!docs.length || busy} onClick={() => execute(async () => { const more = await api(`/erp/documents?before=${docs[docs.length - 1]._id}`); setDocs([...docs, ...more]); })}>Load older documents</button></section>}
    {tab === "Stock" && <section className="erp-card"><h2>Department / work-order stock</h2><Table headings={["SKU", "Location", "Qty", "Value", "Avg unit cost"]} rows={stock.map(b => [b.sku, b.location, q(b.qty), amount(b.value), amount(b.qty ? b.value * 1000 / b.qty : 0)])} /></section>}
    {tab === "Ledger" && <section className="erp-card"><h2>Stock & general ledger · latest 1,000 rows</h2><Table headings={["Date", "Document", "Account / Stock", "Movement", "Debit", "Credit"]} rows={entries.map(e => [new Date(e.date).toLocaleDateString("en-IN"), e.documentNo, e.kind === "STOCK" ? `${e.sku} @ ${e.location}` : e.account, e.kind === "STOCK" ? q(e.delta) : e.party, amount(e.debit), amount(e.credit)])} /></section>}
    {tab === "Financials" && <section className="erp-card"><h2>Financial reports</h2><div className="erp-grid">{["from", "to"].map(k => <Field name={label(k)} key={k}><input type="date" value={reportDates[k]} onChange={e => setReportDates({ ...reportDates, [k]: e.target.value })} /></Field>)}</div><button disabled={busy} onClick={report}>Run report</button>{financials && <>
      <div className="erp-stats"><article><span>Revenue</span><strong>{amount(financials.profitAndLoss.revenue)}</strong></article><article><span>Expenses</span><strong>{amount(financials.profitAndLoss.expenses)}</strong></article><article><span>Profit</span><strong>{amount(financials.profitAndLoss.profit)}</strong></article><article><span>Trial balance difference</span><strong>{amount(financials.trialDifference)}</strong></article></div>
      <h3>Trial balance</h3><Table headings={["Account", "Debit", "Credit", "Balance"]} rows={financials.accounts.map(a => [a.name, amount(a.debit), amount(a.credit), amount(a.balance)])} />
      <h3>Balance sheet</h3><Table headings={["Assets", "Liabilities", "Equity", "Retained earnings", "Difference"]} rows={[[...Object.values(financials.balanceSheet)].map(amount)]} />
      <h3>Party outstanding / credits</h3><Table headings={["Party", "Receivable", "Payable"]} rows={financials.parties.map(p => [p.party, amount(p.receivable), amount(p.payable)])} />
      <h3>Stock/accounting reconciliation</h3><Table headings={["Inventory stock", "Inventory GL", "WIP stock + costs", "WIP GL"]} rows={[[financials.currentReconciliation.inventoryValue, financials.currentReconciliation.inventoryLedger, financials.currentReconciliation.wipValue, financials.currentReconciliation.wipLedger].map(amount)]} /><p>{financials.currentReconciliation.note}. Tax postings are configurable bookkeeping entries; statutory GST filing/e-invoicing needs separate integration.</p>
    </>}</section>}
    {selected && <div className="erp-dialog" role="dialog" aria-modal="true"><div className="erp-document"><div className="erp-noprint"><button onClick={() => setSelected(null)}>Close</button> <button onClick={() => window.print()}>Print / Save PDF</button></div><h2>{selected.metadata?.company?.name || workspace.company.name}</h2><p>{selected.metadata?.company?.address || workspace.company.address} · {workspace.company.factory}</p><p>GSTIN: {selected.metadata?.company?.gstin || "—"}</p><h3>{label(selected.type)}</h3><p><b>{selected.number}</b> · {new Date(selected.date).toLocaleDateString("en-IN")}<br />Party: {selected.partyCode || "—"}<br />Record ID: {selected._id}<br />Source ID: {selected.sourceId || "—"}</p><Table headings={["SKU", "Quantity", "Unit", "Rate", "Net", "Tax"]} rows={selected.lines.map(l => [l.sku, q(l.qty), l.unit, amount(l.rate), amount(l.net), amount(l.tax)])} /><p>Customer / Supplier: {selected.metadata?.party?.name || selected.partyCode || "—"}<br />{selected.metadata?.party?.address || ""}<br />GSTIN: {selected.metadata?.party?.gstin || "—"}</p><p>Total: <b>{amount(selected.totals.gross)}</b></p><p>{selected.notes}</p><p>{selected.metadata?.qcNotes}</p><Table headings={["Account", "Debit", "Credit"]} rows={selected.journals.map(l => [l.account, amount(l.debit), amount(l.credit)])} /><p>Posted by: {selected.postedBy}. {selected.reversedBy ? "REVERSED" : "POSTED"}</p>
      {canAdmin && !selected.reversedBy && selected.type !== "REVERSAL" && <form className="erp-noprint" onSubmit={e => { e.preventDefault(); const reason = e.currentTarget.elements.reason.value; execute(async () => { await api(`/erp/documents/${selected._id}/reverse`, { method: "POST", headers: { "Idempotency-Key": `reverse_${selected._id}` }, body: JSON.stringify({ notes: reason }) }); setSelected(null); await load(); notify("Document reversed"); }); }}><input name="reason" required placeholder="Reversal reason" /><button disabled={busy}>Reverse posted document</button></form>}
      {canAdmin && selected.journals.some(l => l.account === "BANK") && !selected.clearedAt && !selected.reversedBy && <form className="erp-noprint" onSubmit={e => { e.preventDefault(); const f = e.currentTarget.elements; execute(async () => { setSelected(await api(`/erp/documents/${selected._id}/reconcile`, { method: "POST", body: JSON.stringify({ amount: f.amount.value, bankReference: f.reference.value, clearedAt: f.date.value }) })); await load(); }); }}><h4>Match bank statement</h4><input name="amount" type="number" step="0.01" required placeholder="Statement amount INR" /><input name="reference" required placeholder="Bank transaction reference" /><input name="date" type="date" required /><button disabled={busy}>Mark reconciled</button></form>}
    </div></div>}
  </div>;
}
