import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { api } from "../../api.js";
import { useAuth } from "../../context/AuthContext.jsx";
import { companyKeyFromLocation } from "../../utils/tenantClient.js";
import Maintenance from "./Maintenance.jsx";
const base="/erp/operations";
const qty=n=>(Number(n||0)/1000).toLocaleString("en-IN",{maximumFractionDigits:3});
const hours=n=>(Number(n||0)/3600000).toFixed(2);
const day=d=>new Date(d).toLocaleString("en-IN");
function GridTable({head,rows}) { return <div className="erp-table"><table><thead><tr>{head.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>; }
function Input({name,label,type="text",...rest}) { return <label className="erp-field"><span>{label||name}</span><input name={name} type={type} required {...rest}/></label>; }
function Select({name,options,label}) { return <label className="erp-field"><span>{label||name}</span><select name={name} required><option value="">Select…</option>{options.map(o=><option key={o.value||o} value={o.value||o}>{o.label||o}</option>)}</select></label>; }
function download(name,rows) { const csv=rows.map(row=>row.map(v=>'"'+String(v??"").replaceAll('"','""')+'"').join(",")).join("\n"); const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href); }
export function RollView({rollId,onClose}) {
  const [data,setData]=useState(null),[error,setError]=useState(""),[qr,setQr]=useState("");
  const url=`${window.location.origin}/c/${companyKeyFromLocation()}/erp-roll/${rollId}`;
  useEffect(()=>{ api(`${base}/rolls/${rollId}`).then(setData).catch(e=>setError(e.message));QRCode.toDataURL(url,{width:240,margin:2}).then(setQr).catch(e=>setError(e.message)); },[rollId]);
  return <div className="erp-dialog"><div className="erp-document"><div className="erp-noprint">{onClose&&<button onClick={onClose}>Close</button>} <button onClick={()=>window.print()}>Print / Save PDF</button></div><h2>UG SaaS · Roll trace</h2>{error&&<p className="erp-error">{error}</p>}{data?<><h3>{data.roll.rollNo} · {data.roll.sku}</h3><p>Batch: {data.roll.batchNo}<br/>Set: {data.roll.setNo} · DC: {data.roll.dcNo}<br/>Colour: {data.roll.colour} · Dia: {data.roll.dia}<br/>Receipt: {data.receipt?.number} {data.receipt?.reversedBy?"(REVERSED)":""}<br/>Received: {qty(data.roll.receiptQty)} KG</p>{qr&&<a href={url}><img src={qr} alt="Secure roll trace QR" width="200"/></a>}<p>Scan requires login to the same company and factory.</p><GridTable head={["Location","Current quantity KG"]} rows={data.balances.map(b=>[b.location,qty(b.qty)])}/><GridTable head={["Document","Type","Date","Status"]} rows={data.trace.map(d=>[d.number,d.type,day(d.date),d.reversedBy?"Reversed":"Posted"])}/></>:<p>Loading roll…</p>}</div></div>;
}
export default function ShopFloor({notify}) {
  const {user}=useAuth();const [data,setData]=useState(null),[tab,setTab]=useState("Routing"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[events,setEvents]=useState([]),[mrp,setMrp]=useState(null),[selected,setSelected]=useState(null),[roll,setRoll]=useState(null),[week,setWeek]=useState(new Date().toISOString().slice(0,10));
  const admin=["company_admin","admin"].includes(user?.role),write=admin||(user?.permissions||[]).includes("erp.stock"),masters=admin||(user?.permissions||[]).includes("erp.masters");
  async function load(){setData(await api(`${base}/dashboard`));setEvents(await api(`${base}/events`));}
  useEffect(()=>{load().catch(e=>setError(e.message));},[]);
  async function run(action){setBusy(true);setError("");try{await action();}catch(e){setError(e.message);}finally{setBusy(false);}}
  const submit=(endpoint,transform=v=>v)=>e=>{e.preventDefault();const form=e.currentTarget,input=transform(Object.fromEntries(new FormData(form)));const k=form.dataset.requestKey||(form.dataset.requestKey=crypto.randomUUID());run(async()=>{await api(`${base}/${endpoint}`,{method:"POST",headers:{"Idempotency-Key":k},body:JSON.stringify(input)});delete form.dataset.requestKey;form.reset();await load();notify("Shop-floor record saved");});};
  const resetKey=e=>{delete e.currentTarget.dataset.requestKey;};
  if(!data)return <p>{error||"Loading shop floor…"}</p>;
  const orders=data.orders.map(o=>({value:o._id,label:`${o.number} · ${o.lines[0].sku} · ${qty(o.lines[0].qty)}`}));
  const start=new Date(`${week}T00:00:00`),end=new Date(start.getTime()+7*86400000),jobs=data.operations.filter(j=>new Date(j.start)<end&&new Date(j.end)>start);
  return <><nav className="erp-tabs">{["Routing","Machines","Schedule","Weekly report","MRP","Roll QR","Maintenance"].map(t=><button key={t} className={tab===t?"active":""} onClick={()=>{setTab(t);if(t==="MRP")run(async()=>setMrp(await api(`${base}/mrp`)));}}>{t}</button>)}<button disabled={busy} onClick={()=>run(load)}>Refresh</button></nav>{error&&<p className="erp-error">{error}</p>}
    {tab==="Maintenance"&&<Maintenance machines={data.machines} canWrite={masters} notify={notify}/>}
    {tab==="Routing"&&<section className="erp-card"><h2>Order routing & department progress</h2><p>Cutting and Folding are mandatory; Packing is final. Later stages accept only completed previous-stage quantity. Routing does not move stock: material issue and production receipts use the ERP ledger.</p>{write&&<form onChange={resetKey} onSubmit={submit("routing",v=>({...v,stages:v.stages.split(",").map(s=>s.trim().toUpperCase())}))}><div className="erp-grid"><Select name="workOrderId" label="Work order" options={orders}/><Input name="stages" label="Stage order" defaultValue="FABRIC,SPREADING,CUTTING,FOLDING,STITCHING,FINISHING,PACKING"/></div><button disabled={busy}>Freeze work order routing</button></form>}<GridTable head={["Work order","Routing","Progress (completed / planned)"]} rows={data.routes.map(r=>[data.orders.find(o=>o._id===r.workOrderId)?.number||r.workOrderId,r.stages.join(" → "),r.stages.map(s=>`${s}: ${qty(data.operations.filter(j=>j.workOrderId===r.workOrderId&&j.stage===s&&j.status==="COMPLETE").reduce((a,j)=>a+j.qty,0))}/${qty(r.qty)}`).join(" · ")])}/></section>}
    {tab==="Machines"&&<section className="erp-card"><h2>Machine / workstation master</h2>{masters&&<form onSubmit={submit("machines")}><div className="erp-grid"><Input name="code" label="Machine code"/><Input name="name" label="Machine / workstation name"/><Select name="stage" options={data.stages}/></div><button disabled={busy}>Create machine</button></form>}<GridTable head={["Code","Name","Stage"]} rows={data.machines.map(m=>[m.code,m.name,m.stage])}/></section>}
    {tab==="Schedule"&&<section className="erp-card"><h2>Machine assignment & operation entry</h2>{write&&<form onChange={resetKey} onSubmit={submit("operations")}><div className="erp-grid"><Select name="workOrderId" label="Work order" options={orders}/><Select name="stage" options={data.stages}/><Select name="machineCode" label="Machine" options={data.machines.map(m=>({value:m.code,label:`${m.code} · ${m.stage}`}))}/><Input name="quantity" type="number" min="0.001" step="0.001" label="Quantity in work order output unit"/><Input name="start" type="datetime-local" label="Planned start"/><Input name="end" type="datetime-local" label="Planned end"/></div><button disabled={busy}>Assign operation</button></form>}<GridTable head={["Work order","Stage / Machine","Qty","Scheduled","Status","Run / Pause hours","Action"]} rows={data.operations.map(j=>[data.orders.find(o=>o._id===j.workOrderId)?.number||j.workOrderId,`${j.stage} / ${j.machineCode}`,qty(j.qty),`${day(j.start)} → ${day(j.end)}`,j.status,`${hours(j.runMs)} / ${hours(j.pauseMs)}`,write&&!['COMPLETE','CANCELLED'].includes(j.status)?<button onClick={()=>setSelected(j)}>Record event</button>:"—"])}/></section>}
    {tab==="Weekly report"&&<section className="erp-card"><h2>Seven-day Gantt & machine report</h2><Input name="week" type="date" label="Week starts" value={week} onChange={e=>setWeek(e.target.value)}/><p>Bars show planned intervals. Run/pause duration is committed when an event is recorded. Dashboard/report is limited to the latest 2,000 jobs/events.</p><div className="erp-gantt">{jobs.map(j=>{const left=Math.max(0,(new Date(j.start)-start)/(7*86400000)*100),right=Math.min(100,(new Date(j.end)-start)/(7*86400000)*100);return <div key={j._id}><b>{j.machineCode} · {j.stage}</b><div className="erp-gantt-track"><button style={{marginLeft:`${left}%`,width:`${Math.max(1,right-left)}%`}} onClick={()=>setSelected({...j,report:true})}>{j.status}</button></div></div>;})}</div><button onClick={()=>download("machine-week.csv",[["Machine","Stage","WO","Qty","Start","End","Status","Run hours","Pause hours","Reasons"],...jobs.map(j=>[j.machineCode,j.stage,data.orders.find(o=>o._id===j.workOrderId)?.number,qty(j.qty),day(j.start),day(j.end),j.status,hours(j.runMs),hours(j.pauseMs),events.filter(e=>e.operationId===j._id&&e.reason).map(e=>`${e.reason}: ${e.notes}`).join("; ")])])}>Download CSV report</button><button onClick={()=>setSelected({report:true,weekly:true})}>Print weekly report</button></section>}
    {tab==="MRP"&&<section className="erp-card"><h2>Material requirements & shortage suggestions</h2><p>{mrp?.note}</p><GridTable head={["SKU","Unit","Required","Available","Shortage"]} rows={(mrp?.rows||[]).map(r=>[r.sku,r.unit,qty(r.required),qty(r.available),qty(r.shortage)])}/><p>Verify locations, material quality and open purchase commitments before creating a Purchase Order. This report does not reserve stock.</p></section>}
    {tab==="Roll QR"&&<section className="erp-card"><h2>Physical roll register & secure QR</h2><p>Use one distinct RAW KG SKU per physical roll. Quantity comes from the posted receipt; live balances come from the existing ledger. Same DC/colour/dia/fabric uses one batch, and each DC uses one Set No.</p>{write&&<form onSubmit={submit("rolls")}><div className="erp-grid">{["sku","receiptId","rollNo","fabricCode","colour","dcNo","dia","setNo"].map(n=><Input name={n} key={n}/>)}</div><button disabled={busy}>Register roll</button></form>}<GridTable head={["Roll","SKU","Batch","Set","Received KG","Trace"]} rows={data.rolls.map(r=>[r.rollNo,r.sku,r.batchNo,r.setNo,qty(r.receiptQty),<button onClick={()=>setRoll(r._id)}>QR / Print / Trace</button>])}/></section>}
    {selected&&<div className="erp-dialog"><div className="erp-document"><div className="erp-noprint"><button onClick={()=>setSelected(null)}>Close</button><button onClick={()=>window.print()}>Print / PDF</button></div><h2>{selected.weekly?"Weekly machine report":`${selected.stage} · ${selected.machineCode}`}</h2>{selected.weekly?<GridTable head={["Machine","Stage","Work order","Qty","Schedule","Status","Run / Pause hours","Reasons"]} rows={jobs.map(j=>[j.machineCode,j.stage,data.orders.find(o=>o._id===j.workOrderId)?.number,qty(j.qty),`${day(j.start)} → ${day(j.end)}`,j.status,`${hours(j.runMs)} / ${hours(j.pauseMs)}`,events.filter(e=>e.operationId===j._id&&e.reason).map(e=>`${e.reason}: ${e.notes}`).join("; ")])}/>:<><p>Qty: {qty(selected.qty)} · Status: {selected.status}<br/>Planned: {day(selected.start)} → {day(selected.end)}</p><GridTable head={["Time","Action","Reason","Notes","User"]} rows={events.filter(e=>e.operationId===selected._id).map(e=>[day(e.at),e.action,e.reason,e.notes,e.actor])}/>{!selected.report&&write&&<form className="erp-noprint" onChange={resetKey} onSubmit={e=>{e.preventDefault();const form=e.currentTarget,input={...Object.fromEntries(new FormData(form)),revision:selected.revision};const k=form.dataset.requestKey||(form.dataset.requestKey=crypto.randomUUID());run(async()=>{await api(`${base}/operations/${selected._id}/events`,{method:"POST",headers:{"Idempotency-Key":k},body:JSON.stringify(input)});setSelected(null);await load();notify("Operation event saved");});}}><Select name="action" options={selected.status==="PLANNED"?["START","CANCEL"]:selected.status==="RUNNING"?["PAUSE","COMPLETE"]:["RESUME"]}/><label className="erp-field"><span>Pause reason</span><select name="reason"><option value="">—</option>{["BREAKDOWN","CHANGEOVER","TRANSFER","MATERIAL","OTHER"].map(x=><option key={x}>{x}</option>)}</select></label><Input name="notes" label="Event notes"/><button disabled={busy}>Record event</button></form>}</>}</div></div>}{roll&&<RollView rollId={roll} onClose={()=>setRoll(null)}/>}</>;
}
