import { Router } from "express";
import { allowRoles } from "../middleware/roleMiddleware.js";
import { asyncHandler } from "../utils/asyncHandler.js";
import { approveBom, dashboard, deleteBom, listBoms, listMovements, listPos, materialStatus, saveBom, saveMovement, savePo, uploadPos } from "../controllers/garmentController.js";

const router = Router();
const all = allowRoles("saas_super_admin", "company_admin", "admin", "store", "production", "production_planner", "production_operator", "supervisor", "quality", "maintenance", "sewing_coordinator", "management", "view_only");
const admin = allowRoles("saas_super_admin", "company_admin", "admin");
router.use(all);
router.get("/dashboard", asyncHandler(dashboard));
router.get("/boms", asyncHandler(listBoms));
router.post("/boms", asyncHandler(saveBom));
router.put("/boms/:id", asyncHandler(saveBom));
router.patch("/boms/:id/approval", admin, asyncHandler(approveBom));
router.delete("/boms/:id", admin, asyncHandler(deleteBom));
router.get("/pos", asyncHandler(listPos));
router.post("/pos", asyncHandler(savePo));
router.post("/pos/upload", asyncHandler(uploadPos));
router.get("/materials-status", asyncHandler(materialStatus));
router.get("/movements", asyncHandler(listMovements));
router.post("/movements", asyncHandler(saveMovement));
export default router;
