import { useEffect, useMemo, useState } from "react";
import { Building2, ChevronDown, ChevronRight, Factory, Plus, ShieldCheck, Users } from "lucide-react";
import { api } from "../../api.js";
import Card from "../../components/common/Card.jsx";
import PageTitle from "../../components/common/PageTitle.jsx";

const newUser = { name:"",email:"",password:"",role:"store" };
export default function SuperAdminDashboardPage({ notify }) {
  const [companies,setCompanies]=useState([]); const [workspace,setWorkspace]=useState(null); const [openDepartment,setOpenDepartment]=useState(""); const [form,setForm]=useState(newUser);
  const load=async()=>setCompanies(await api("/companies")); useEffect(()=>{load();},[]);
  async function openCompany(company){setWorkspace(await api(`/companies/${company._id}/workspace`));setOpenDepartment("");}
  async function createUser(event){event.preventDefault();await api("/auth/users",{method:"POST",body:JSON.stringify({...form,companyId:workspace.company._id,factoryId:workspace.company.factories?.[0]?._id})});setForm(newUser);await openCompany(workspace.company);notify("Company user created");}
  async function toggleUser(user){await api(`/companies/${workspace.company._id}/users/${user._id}`,{method:"PATCH",body:JSON.stringify({active:!user.active})});await openCompany(workspace.company);notify(user.active?"User disabled":"User activated");}
  const totals=useMemo(()=>({companies:companies.length,active:companies.filter(c=>c.active&&c.subscriptionStatus==="Active").length,users:companies.reduce((sum,c)=>sum+(c.userCount||0),0),trials:companies.filter(c=>c.subscriptionPlan==="Trial").length}),[companies]);
  if(workspace)return <><button className="owner-back" onClick={()=>setWorkspace(null)}>← All Companies</button><PageTitle title={workspace.company.companyName} subtitle={`${workspace.company.subscriptionPlan} · ${workspace.company.subscriptionStatus}`}/><div className="company-workspace-summary"><div><Factory/><span><small>Factories</small><b>{workspace.company.factories?.length||0}</b></span></div><div><Users/><span><small>Users</small><b>{workspace.users.length}</b></span></div><div><ShieldCheck/><span><small>Subscription</small><b>{workspace.company.subscriptionStatus}</b></span></div></div><Card title="Department Access & Users"><div className="department-accordion">{Object.entries(workspace.departments).map(([department,users])=><section key={department}><button onClick={()=>setOpenDepartment(openDepartment===department?"":department)}>{openDepartment===department?<ChevronDown/>:<ChevronRight/>}<span><b>{department}</b><small>{users.length} users</small></span></button>{openDepartment===department&&<div className="department-users">{users.length?users.map(user=><div key={user._id}><span><b>{user.name}</b><small>{user.email}</small></span><code>{user.role}</code><span className={user.active?"status-green":"status-red"}>{user.active?"Active":"Disabled"}</span><button onClick={()=>toggleUser(user)}>{user.active?"Disable":"Activate"}</button></div>):<p>No users in this department.</p>}</div>}</section>)}</div></Card><Card title="Add User to This Company"><form className="owner-user-form" onSubmit={createUser}><input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="8" type="password" placeholder="Temporary password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{["company_admin","admin","store","production","production_planner","production_operator","supervisor","quality","maintenance","sewing_coordinator","management","view_only"].map(role=><option key={role}>{role}</option>)}</select><button className="primary"><Plus/> Create User</button></form></Card></>;
  return <><PageTitle title="SaaS Owner Dashboard" subtitle="Companies, users, subscriptions and department access"/><div className="owner-stats"><div><Building2/><span><small>Total Companies</small><b>{totals.companies}</b></span></div><div><ShieldCheck/><span><small>Active Companies</small><b>{totals.active}</b></span></div><div><Users/><span><small>Total Users</small><b>{totals.users}</b></span></div><div><Factory/><span><small>Trial Companies</small><b>{totals.trials}</b></span></div></div><Card title="Company Workspaces"><div className="company-flex-grid">{companies.map(company=><button key={company._id} onClick={()=>openCompany(company)}><div className="company-card-icon"><Building2/></div><div><h3>{company.companyName}</h3><p>{company.factories?.map(f=>f.name).join(", ")||"No factory"}</p></div><span className={company.active&&company.subscriptionStatus==="Active"?"company-active":"company-inactive"}>{company.subscriptionStatus}</span><footer><small>{company.subscriptionPlan} Plan</small><small>{company.activeUsers||0}/{company.userCount||0} active users</small></footer></button>)}</div></Card></>;
}
